---
site_name: Strata Cloud Manager Ansible Collection
site_description: Ansible Collection to manage Palo Alto Networks Strata Cloud Manager configurations
site_url: https://cdot65.github.io/pan-scm-ansible/
repo_url: https://github.com/cdot65/pan-scm-ansible
repo_name: cdot65/pan-scm-ansible
site_dir: site
copyright: Copyright &copy; 2023-2025 Calvin Remsburg

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - termynal
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
          selection:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - footnotes

# Explicitly set the layout for home page with customizations
not_in_nav: |
  index.md
  STYLE_GUIDE.md

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

# Define the navigation menu
nav:
  - Home: index.md
  - About:
      - Introduction: about/introduction.md
      - Installation: about/installation.md
      - Getting Started: about/getting-started.md
      - Troubleshooting: about/troubleshooting.md
      - Contributing: about/contributing.md
      - Release Notes: about/release-notes.md
      - License: about/license.md
  - Collection:
      - Overview: collection/index.md
      - Modules:
          - Overview: collection/modules/index.md
          - Network Objects:
              - Address: collection/modules/address.md
              - Address Info: collection/modules/address_info.md
              - Address Group: collection/modules/address_group.md
              - Address Group Info: collection/modules/address_group_info.md
              - Application: collection/modules/application.md
              - Application Info: collection/modules/application_info.md
              - Application Group: collection/modules/application_group.md
              - Application Group Info: collection/modules/application_group_info.md
              - Dynamic User Group: collection/modules/dynamic_user_group.md
              - External Dynamic Lists: collection/modules/external_dynamic_lists.md
              - External Dynamic Lists Info: collection/modules/external_dynamic_lists_info.md
              - Service: collection/modules/service.md
              - Service Info: collection/modules/service_info.md
              - Service Group: collection/modules/service_group.md
              - Service Group Info: collection/modules/service_group_info.md
              - Tag: collection/modules/tag.md
              - Tag Info: collection/modules/tag_info.md
          - Network Configuration:
              - Security Zone: collection/modules/security_zone.md
              - IKE Crypto Profile: collection/modules/ike_crypto_profile.md
              - IKE Gateway: collection/modules/ike_gateway.md
              - IPsec Crypto Profile: collection/modules/ipsec_crypto_profile.md
              - IPsec Tunnel: collection/modules/ipsec_tunnel.md
              - BGP Routing: collection/modules/bgp_routing.md
          - Deployment:
              - Remote Networks: collection/modules/remote_networks.md
              - Network Locations: collection/modules/network_locations.md
              - Service Connections: collection/modules/service_connections.md
          - Security Services:
              - Anti-Spyware Profile: collection/modules/anti_spyware_profile.md
              - Anti-Spyware Profile Info: collection/modules/anti_spyware_profile_info.md
              - Security Profiles Group: collection/modules/security_profiles_group.md
              - Security Rule: collection/modules/security_rule.md
              - Security Rule Info: collection/modules/security_rule_info.md
      - Roles:
          - Overview: collection/roles/index.md
          - Bootstrap: collection/roles/bootstrap.md
          - Deploy Configuration: collection/roles/deploy_config.md
      - Plugins:
          - Overview: collection/plugins/index.md
          - Inventory: collection/plugins/inventory.md
          - Lookup: collection/plugins/lookup.md
  - User Guide:
      - Getting Started: guide/getting-started.md
      - Authentication: guide/authentication.md
      - Using Modules: guide/using-modules.md
      - Using Roles: guide/using-roles.md
      - Playbook Examples: guide/playbook-examples.md
      - Advanced Topics: guide/advanced-topics.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - Release Process: development/release-process.md
      - Ansible Compatibility: development/ansible_compatibility.md
