---
authors:
  - Calvin Remsburg <calvin@cdot.io>
description: Ansible Collection for managing SCM with pan-scm-sdk.
dependencies: {}
documentation: https://github.com/cdot65/pan-scm-ansible-collection/blob/main/pan_scm_ansible_collection/README.md
homepage: https://github.com/cdot65/pan-scm-ansible-collection/
issues: https://github.com/cdot65/pan-scm-ansible-collection/issues
license:
  - MIT
namespace: cdot65
name: scm
repository: https://github.com/cdot65/pan-scm-ansible-collection
readme: README.md
tags:
  - stratacloudmanager
  - firewall
  - networksecurity
  - cybersecurity
  - infrastructure
  - paloaltonetworks
  - panos
  - automation
  - networkautomation
version: 0.1.0
build_ignore:
  - tools
  - setup.cfg
  - galaxy.yml.j2
  - template_galaxy.yml
  - '*.tar.gz'